.TH qlibs: getoptb 3
.SH NAME
getoptb \- get option character from command line
.SH SYNTAX
.B #include \(dqgetoptb.h\(dq
.SH DESCRIPTION
Qlib's
.B getopt
is a replacement for the standard Unix
.B getopt
library, based on 
.B sgetopt 
and printing errors by means of
.B buffer
rather than
.BR stdio .

See
.B getopt(3)
for interface details.
.SH "SEE ALSO"
buffer(3)
